# Generated by Django 4.2 on 2025-02-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_job_choices_profile_looking_for_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_choices',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_role',
            field=models.CharField(blank=True, choices=[('bus_driver', 'Bus driver'), ('chauffeur', 'Chauffeur'), ('delivery_commerce', 'Delivery (commerce)'), ('emergency_medical_technician', 'Emergency medical technician (ambulance driver)'), ('motorman', 'Motorman (tram/streetcar driver)'), ('pay_driver', 'Pay driver'), ('racing_driver', 'Racing driver'), ('taxicab_driver', 'Taxicab driver'), ('test_driver', 'Test driver'), ('train_driver', 'Train driver'), ('truck_driver', 'Truck driver'), ('pilot', 'Pilot'), ('valet_parking', 'Valet Parking'), ('on_road_professional', 'On-road professional'), ('class1', 'Class 1'), ('class2', 'Class 2'), ('7_5_tonne', '7.5 tonne')], max_length=50, null=True),
        ),
    ]
