# Generated by Django 4.2 on 2025-02-10 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_description', models.TextField()),
                ('working_days', models.CharField(max_length=255)),
                ('working_hours', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='company_documents/')),
                ('description', models.CharField(max_length=255)),
                ('employer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employer.employerprofile')),
            ],
        ),
    ]
