# Generated by Django 4.2 on 2025-02-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_remove_jobpost_documents_jobpost_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='address',
            field=models.CharField(default='No address provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='pay_rate',
            field=models.CharField(max_length=255),
        ),
    ]
