# Generated by Django 4.2 on 2025-02-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_alter_jobpost_address_alter_jobpost_pay_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='jobpost_documents/'),
        ),
    ]
