# Generated by Django 4.2 on 2025-02-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='job_application',
        ),
    ]
