# Generated by Django 4.2 on 2025-02-13 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_alter_jobpost_address_alter_jobpost_pay_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_remove_profile_job_choices_profile_preferred_role'),
        ('review', '0002_remove_review_job_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employerprofile')),
                ('worker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='review.userreview')),
            ],
        ),
    ]
