# Generated by Django 4.2 on 2025-02-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0005_alter_jobpost_address_alter_jobpost_pay_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='employer.jobapplication')),
            ],
            options={
                'unique_together': {('job_application', 'status')},
            },
        ),
    ]
