# Generated by Django 4.2 on 2025-02-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplicationstatus',
            unique_together=set(),
        ),
    ]
